---
- hosts: leafs
  become: yes
  roles:
    - ifupdown2
    - frr

- hosts: spines
  become: yes
  roles:
    - ifupdown2
    - frr

- hosts: servers
  become: yes
  roles:
    - ifupdown
    - frr-roh

