---
- hosts: leafs
  become: yes
  roles:
    - ifupdown2
    - quagga

- hosts: spines
  become: yes
  roles:
    - ifupdown2
    - quagga

- hosts: servers
  become: yes
  roles:
    - ifupdown
    - quagga-roh

