# This command actually restarts quagga. This command will actually drop all
# routes currently in progress, so this will interrupt networking currently in
# place.
- name: restart frr
  service: 
    name: frr 
    state: restarted
